service: ${env:SERVICE_NAME}

useDotenv: true
variablesResolutionMode: 20210219
configValidationMode: error

package:
  patterns:
    - "index.js"
    - "node_modules/**"
    - "util/**"

provider:
  name: aws
  # The stage of the application, e.g. dev, production, staging…
  stage: ${opt:stage,"development"}
  tags:
    ManagedBy: Serverless
    Project: ${env:PROJECT_NAME,env:SERVICE_NAME}
  iam:
    role: ${env:SERVERLESS_ROLE}
  runtime: nodejs18.x
  versionFunctions: false
  deploymentBucket:
    name: ${env:DEPLOYMENT_BUCKET}
  lambdaHashingVersion: 20201221
  apiGateway:
    binaryMediaTypes:
      - "*/*"
  environment:
    BUCKET: ${env:BUCKET}
    IMAGE_ACL: ${env:IMAGE_ACL,""}
    IMAGE_QUALITY: ${env:IMAGE_QUALITY,80}

functions:
  main:
    handler: index.handler
    description: "Scale images at runtime."
    events:
      - http:
          path: resize
          method: get

resources:
  extensions:
    MainLogGroup:
      Properties:
        RetentionInDays: "14"
        Tags:
          - Key: "ManagedBy"
            Value: "Serverless"
          - Key: "Project"
            Value: ${env:PROJECT_NAME,env:SERVICE_NAME}
