service: ${env:SERVICE_NAME,"imageScaler"}

useDotenv: true
variablesResolutionMode: 20210219
configValidationMode: error

provider:
  name: aws
  # The AWS region in which to deploy (us-east-1 is the default)
  region: ${env:AWS_REGION,opt:region}
  # The stage of the application, e.g. dev, production, staging…
  stage: ${opt:stage,"development"}
  tags:
    ManagedBy: Serverless
    Project: ${env:PROJECT_NAME,env:SERVICE_NAME}
  iam:
    role: ${env:SERVERLESS_ROLE}
  runtime: nodejs16.x
  deploymentBucket:
    name: ${env:DEPLOYMENT_BUCKET}
  lambdaHashingVersion: 20201221
  apiGateway:
    binaryMediaTypes:
      - "*/*"
  environment:
    BUCKET: ${env:BUCKET}
    IMAGE_ACL: ${env:IMAGE_ACL,""}
    IMAGE_QUALITY: ${env:IMAGE_QUALITY}

functions:
  main:
    handler: index.handler
    description: "Scale images at runtime."
    events:
      - http:
          path: resize
          method: get

resources:
  extensions:
    MainLogGroup:
      Properties:
        RetentionInDays: "14"
        Tags:
          - Key: "ManagedBy"
            Value: "Serverless"
          - Key: "Project"
            Value: ${env:PROJECT_NAME,env:SERVICE_NAME}
